
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ertan		
 */
public class StokUygulamasi extends javax.swing.JFrame {

	/**
	 * Creates new form StokUygulamasi
	 */
	public StokUygulamasi() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		urunIsmiTf = new javax.swing.JTextField();
		kategori_cb = new javax.swing.JComboBox<>();
		fiyatTf = new javax.swing.JTextField();
		btnUrunEkle = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		urunTable = new javax.swing.JTable();
		jLabel4 = new javax.swing.JLabel();
		mesajAlani = new javax.swing.JLabel();
		btnGuncelle = new javax.swing.JButton();
		btnSil = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Product Name ");

		jLabel2.setText("Category: ");

		jLabel3.setText("Price: ");

		kategori_cb.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Kultur-Sanat", "Yemek", "Elektronik" }));

		btnUrunEkle.setText("Add");
		btnUrunEkle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUrunEkleActionPerformed(evt);
			}
		});

		urunTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Product Name", "Category", "Price" }));
		urunTable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				urunTableMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(urunTable);

		mesajAlani.setForeground(new java.awt.Color(204, 0, 0));

		btnGuncelle.setText("Update");
		btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGuncelleActionPerformed(evt);
			}
		});

		btnSil.setText("Delete");
		btnSil.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSilActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(60, 60, 60)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(urunIsmiTf, javax.swing.GroupLayout.PREFERRED_SIZE, 167,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2).addComponent(jLabel3))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(kategori_cb, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(fiyatTf))))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(btnUrunEkle, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 132,
												Short.MAX_VALUE)
										.addComponent(btnSil, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(37, 37, 37))
				.addGroup(layout.createSequentialGroup().addGap(81, 81, 81)
						.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 306,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(24, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap())
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(mesajAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 334,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(146, 146, 146)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(44, 44, 44)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(urunIsmiTf, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnUrunEkle))
				.addGap(14, 14, 14)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(kategori_cb, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnGuncelle))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(fiyatTf, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnSil))
				.addGap(16, 16, 16).addComponent(mesajAlani)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel4)
				.addGap(31, 31, 31).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(66, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnUrunEkleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUrunEkleActionPerformed
		mesajAlani.setText(" ");
		DefaultTableModel model = (DefaultTableModel) urunTable.getModel();
		if (urunIsmiTf.getText().trim().equals("")) {
			mesajAlani.setText("Product Name not empty...");
		} else if (fiyatTf.getText().trim().equals("")) {
			mesajAlani.setText("Price not empty...");
		} else {
				
			Object[] eklenecek = { urunIsmiTf.getText(), kategori_cb.getSelectedItem().toString(), fiyatTf.getText() };
			model.addRow(eklenecek);
		}
	}// GEN-LAST:event_btnUrunEkleActionPerformed

	private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuncelleActionPerformed
		mesajAlani.setText(" ");
		DefaultTableModel model = (DefaultTableModel) urunTable.getModel();

		int seciliRow = urunTable.getSelectedRow();
		if (seciliRow == -1) {
			if (urunTable.getRowCount() == 0) {
				mesajAlani.setText("Product Empty");
			} else {
				mesajAlani.setText("Product Not Selected.");
			}
		} else {
			model.setValueAt(urunIsmiTf.getText(), seciliRow, 0);
			model.setValueAt(kategori_cb.getSelectedItem(), seciliRow, 1);
			model.setValueAt(fiyatTf.getText(), seciliRow, 2);

			mesajAlani.setText("Product updated.");
		}
	}// GEN-LAST:event_btnGuncelleActionPerformed

	private void urunTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_urunTableMouseClicked
		DefaultTableModel model = (DefaultTableModel) urunTable.getModel();

		int seciliRow = urunTable.getSelectedRow();

		urunIsmiTf.setText(model.getValueAt(seciliRow, 0).toString());
		kategori_cb.setSelectedItem(model.getValueAt(seciliRow, 1).toString());
		fiyatTf.setText(model.getValueAt(seciliRow, 2).toString());
	}// GEN-LAST:event_urunTableMouseClicked

	private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSilActionPerformed
		mesajAlani.setText(" ");
		DefaultTableModel model = (DefaultTableModel) urunTable.getModel();

		int seciliRow = urunTable.getSelectedRow();
		if (seciliRow == -1) {
			if (urunTable.getRowCount() == 0) {
				mesajAlani.setText("Product Empty");
			} else {
				mesajAlani.setText("Product Not Selected.");
			}
		} else {
			model.removeRow(seciliRow);
			mesajAlani.setText("Product Deleted..");
		}
	}// GEN-LAST:event_btnSilActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StokUygulamasi().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnGuncelle;
	private javax.swing.JButton btnSil;
	private javax.swing.JButton btnUrunEkle;
	private javax.swing.JTextField fiyatTf;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JComboBox<String> kategori_cb;
	private javax.swing.JLabel mesajAlani;
	private javax.swing.JTextField urunIsmiTf;
	private javax.swing.JTable urunTable;
	// End of variables declaration//GEN-END:variables
}
